logging:
  level:
    root: debug
    com.rest.api: debug

spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      hbm2ddl.auto: update
      format_sql: true
    showSql: true
    generate-ddl: true
  url:
    base: http://localhost:8080
  redis:
    host: localhost
    port: 6379